sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "fullbloomh3ck@gmail.com"
  - git config --global user.name "seonghbae"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "N3PnEXHeJXAJn3XDnX6Qx8dZVPRx9/ovDHDnBJTPb/QUneOmlwJfrKyxW4e4R3PDFSTIeYWZPa7oPBYg
             yX/JUORjfHyqAyiH4QJ3RhaIYFytC+i2x82OqKvYCzkwepekad2azxlI+40XekZcWdp2hB2N/eY7L+4Mx8JJ2F1BRZc
             qx8TLPqZcPcqj0ld2Btz9GZZ/5itK5SDTRzHMzg72LWlEgZn8h5hTH2Sc92nuAp1V0FRNGN49UaklCJlXPZzhV+zB4g
             wpBhd+fRyT/bghlcAhl2J7ylantoDysdqZwIH5PlVEVWuiQKIGQ0ZfNWaMOu//uFszQ8G00lXe72BZYDzO+lYE4ZqZM
             A3e7lxUq2QuYiAsY6Jmyk3rhZD+dOtQ74ivcgNIEcn/6jwxYfwYfPdAqDEQRY9GUgUApFcfgUm/1t+7ErqBRWbpdqBV
             rFtQySx6ZhMtQ/o5Et7yZ/hOkWC2YnrGTsAeEyxjiOYWf7qngkN4UtzUINyTcTqM6lI8XB+0o0LiHVCkzSkhUU6mDcC
             WKJWCi4o6raVClbwD9vNHG45fu85WW8GDkJWVZF4K1hcVRLsR/uo6FZ0jQWcR0Ye5bb2QF0W+LX1YyuMAYLuxA42Og/
             aAWbGtSxN077wWz0ZIUmgg2SCR1VUljyHSoSVi8yaae4pX0y5nJmq/QBM="
branches:
  only:
    - master